In [2]:
import numpy as np
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

### dataset loading

In [3]:
final = pd.read_csv('/content/sample_data/insurance.csv')
df = final.copy()
print(df)

FileNotFoundError: [Errno 2] No such file or directory: '/content/sample_data/insurance.csv'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
df.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
df['charges']

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [ ]:
df['region'].unique()

array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

# pre processing

In [ ]:
le_sex = LabelEncoder()
le_smoker = LabelEncoder()
le_region = LabelEncoder()

df['sex'] = le_sex.fit_transform(df['sex'])
df['smoker'] = le_smoker.fit_transform(df['smoker'])
df['region'] = le_region.fit_transform(df['region'])

In [ ]:
# Split features and target
X = df[['age', 'sex', 'bmi', 'children', 'smoker', 'region']]
y = df['charges']

In [ ]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# model fitting

In [ ]:
gbr = GradientBoostingRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=3,
    random_state=42
)

In [ ]:
gbr.fit(X_train, y_train)

GradientBoostingRegressor(learning_rate=0.05, n_estimators=200, random_state=42)

# evaluation

In [ ]:
y_pred = gbr.predict(X_test)

In [ ]:
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("R² Score:", r2)

MAE: 2410.164559361616
R² Score: 0.8801237440610301

In [ ]:
from sklearn.metrics import root_mean_squared_error

rmse = root_mean_squared_error(y_test,y_pred)
print(rmse)

4314.004713779095

In [4]:

#Function
def insurance_charge_predictor():
    print("\n--- Insurance Charge Predictor ---")

    age = int(input("Age: "))
    sex = int(input("Sex (0 = Female, 1 = Male): "))
    bmi = float(input("BMI: "))
    children = int(input("Number of children: "))
    smoker = int(input("Smoker (0 = No, 1 = Yes): "))
    region = int(input(
        "Region (0 = Northeast, 1 = Northwest, 2 = Southeast, 3 = Southwest): "
    ))

    cus_input = np.array([[age, sex, bmi, children, smoker, region]])

    usd_charges = gbr.predict(cus_input)[0]
    usd_charges = max(0, usd_charges)  # prevent negative output

    INR_RATE = 83  # USD → INR
    yearly_inr = usd_charges * INR_RATE
    monthly_inr = yearly_inr / 12

    print("\nEstimated Insurance Charges")
    print("---------------------------")
    print(f"Yearly: ₹{yearly_inr:,.2f}")
    print(f"Monthly: ₹{monthly_inr:,.2f}")

    insurance_charge_predictor()

In [5]:
joblib.dump(gbr, 'Insuarance(gbr).pkl')

NameError: name 'gbr' is not defined